name: show_bazzar
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animations: ^2.0.8
  audio_video_progress_bar: ^2.0.2
  
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  chewie: ^1.8.1
  cupertino_icons: ^1.0.6
  dob_input_field: ^2.0.0
  dotted_border: ^2.1.0
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_staggered_grid_view: ^0.7.0
  gender_picker: ^1.1.0
  get: ^4.6.5
  google_fonts: ^6.2.1
  http: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^1.0.8
  input_quantity: ^2.3.2
  intl: ^0.18.1
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.11
  logger: ^2.0.1
  marquee: ^2.2.3
  provider: ^6.1.2
  readmore: ^3.0.0
  rxdart: ^0.27.7
  simple_animations: ^5.0.2
  smooth_page_indicator: ^1.1.0
  speech_to_text: ^6.6.1
  url_launcher: ^6.1.12
  video_player: ^2.8.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/shoes/
    - images/iphone/
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - lib/Stream/images/
    - lib/Stream/videos/
    - lib/Stream/images/Profile/
    - lib/Stream/images/podcasts/
    - lib/Stream/images/live/
    - lib/Stream/images/reels/
    - assets/audio/
    #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
